import React, { useState, useEffect } from 'react'
import { Form, Formik, Field, useField, ErrorMessage } from 'formik'
import * as Yup from 'yup'
import SelectField from '../CustomSelect'
// import SelectNameField from './CustomSelect'
import Select from 'react-select'



const registrationSchema = Yup.object().shape({
    payer: Yup.string()
        .required('Individual Name is required'),
    note: Yup.string()
        .required('Individual Name is required')
        .max(100, 'Maximum 100 letters required'),

})

const BillingProviderOptions = [
    { label: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)', value: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)' }
]
const RenderingProviderOptions = [
    { label: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)', value: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)' }
]
const NoteReferenceCode = [
    { label: 'ADD-Additional Information', value: 'ADD-Additional Information' },
    { label: 'UPI-Updated Information', value: 'UPI-Updated Information' },
]
const ReferringProviderOptions = [
    { label: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)', value: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)' }

]
const ServiceFacilityOptions = [
    { label: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)', value: 'Guardian Haven Academy (EIN: 825356921, PCN# 100069300)' },
]
const SignatureOptions = [
    { label: 'Yes', value: 'Yes' },
    { label: 'No', value: 'No' },
]
const PlaceOptions = [

    { label: '02-Telehealth', value: '02-Telehealth' },
    { label: '03-School', value: '03-School' },
    { label: '04-Homeless Shelter', value: '04-Homeless Shelter' },
    { label: '05-Indian Health Service Free-standing Facility', value: '05-Indian Health Service Free-standing Facility' },
    { label: '06-Indian Health Service Provider-based Facility', value: '06-Indian Health Service Provider-based Facility' },
    { label: '07-Tribal 638 Free-standing Facility', value: '07-Tribal 638 Free-standing Facility' },
    { label: '08-Tribal 638 Provider-based Facility', value: '08-Tribal 638 Provider-based Facility' },
    { label: '10-Unassigned', value: '10-Unassigned' },



]
const FrequencyTypeOptions = [
    { label: '1-Original (Admit thru Discharge Claim)', value: '1-Original (Admit thru Discharge Claim)' },
    { label: '2-Interim - First Claim', value: '2-Interim - First Claim' },
    { label: '3-Interim - Continuing Claim', value: '3-Interim - Continuing Claim' },
    { label: '4-Interim - Last Claim', value: '4-Interim - Last Claim' },
    { label: '6-Corrected (Adjustment of Prior Claim)', value: '6-Corrected (Adjustment of Prior Claim)' },
    { label: '7-Replacement (Replacement of Prior Claim)', value: '7-Replacement (Replacement of Prior Claim)' },
    { label: '8-Void (Void/Cancel of Prior Claim)', value: '8-Void (Void/Cancel of Prior Claim)' },

]
const MedicareAssignmentOptions = [
    { label: 'A-Assigned', value: 'A-Assigned' },
    { label: 'B-Assignment Accepted on Clinical Lab Services Only', value: 'B-Assignment Accepted on Clinical Lab Services Only' },
    { label: 'C-Not Assigned', value: 'C-Not Assigned' },
    { label: 'P-Patient Refuses to Assign Benefits', value: 'P-Patient Refuses to Assign Benefits' },
]
const InformationOptions = [
    { label: 'A-Appropriate Release of Information on File at Health Care Service Provider', value: 'A-Appropriate Release of Information on File at Health Care Service Provider' },
    { label: 'I-Informed Consent to Release Medical Information for Diagnoses', value: 'I-Informed Consent to Release Medical Information for Diagnoses' },
    { label: 'M-The Provider has Limited or Restricted Ability to Release Data Related to a Claim', value: 'M-The Provider has Limited or Restricted Ability to Release Data Related to a Claim' },
    { label: 'N-No, Provider is not Allowed to Release Data.', value: 'N-No, Provider is not Allowed to Release Data.' },
    { label: 'O-On File at Payor or at Plan Sponsor', value: 'O-On File at Payor or at Plan Sponsor' },
    { label: 'Y-Yes, Provider has a Signed Statement Permitting Release of Medical Billing Related to a Claim', value: 'Y-Yes, Provider has a Signed Statement Permitting Release of Medical Billing Related to a Claim' },
]
const PatientSignatureOptions = [
    { label: 'B-Signed Signature Authorization Form or Forms are on File', value: 'B-Signed Signature Authorization Form or Forms are on File' },
    { label: 'C-Signed HCFA-1500 Claim Form on File', value: 'C-Signed HCFA-1500 Claim Form on File' },
    { label: 'P-Signature generated by Provider because the Patient was not Physically Present for Services', value: 'P-Signature generated by Provider because the Patient was not Physically Present for Services' },
]
const FillingIndicatorOptions = [
    { label: 'Medicaid', value: 'Medicaid' },
]
const BenefitsIndicatorOptions = [
    { label: 'Yes', value: 'Yes' },
    { label: 'No', value: 'No' },
]
const PayerOptions = [
    { label: 'Primary', value: 'Primary' },
    { label: 'Secondary', value: 'Secondary' },
    { label: 'Tertiary', value: 'Tertiary' },
    { label: 'Unknown', value: 'Unknown' },
]
const RelationOptions = [
    { label: 'Spouse', value: 'Spouse' },
    { label: 'Self', value: 'Self' },
    { label: 'Child', value: 'Child' },
    { label: 'Employee', value: 'Employee' },
    { label: 'Unknown', value: 'Unknown' },
    { label: 'Life Partner', value: 'Life Partner' },
    { label: 'Other RelationShip', value: 'Other RelationShip' },
]
const SpecialProgramOptions = [
    { label: '03-Special Federal Funding', value: '03-Special Federal Funding' },
]
const Payer = [
    { label: 'FL MMIS: Florida Medicaid - 77027 (Prof.)', value: 'FL MMIS: Florida Medicaid - 77027 (Prof.)' },
    { label: 'THERAP-MANUAL: Manual Billing - 99 (Prof. & Inst.)', value: 'THERAP-MANUAL: Manual Billing - 99 (Prof. & Inst.)' },
]
const data = [
    { label: 'Algood, Shane / 0000004038', value: 'Algood, Shane / 0000004038' },
    { label: 'Alvarez, Jessenia / 0000211534', value: 'Alvarez, Jessenia / 0000211534' },
    { label: 'Ambrose, Shelley / 0000176739 ', value: 'Ambrose, Shelley / 0000176739 ' },
    { label: 'Andrews, Isaac / 0043818', value: 'Andrews, Isaac / 0043818' }
]
const DelayReasonCode = [
    { label: '1-Proof of Eligibility Unknown or Unavailable', value: '1-Proof of Eligibility Unknown or Unavailable' },
    { label: '2-Litigation', value: '2-Litigation' },
    { label: '3-Authorization Delays', value: '3-Authorization Delays' },
    { label: '4-Delay in Certifying Provider', value: '4-Delay in Certifying Provider' },
    { label: '5-Delay in Supplying Billing Forms', value: '5-Delay in Supplying Billing Forms' },
    { label: '6-Delay in Delivery of Custom-made Appliances', value: '6-Delay in Delivery of Custom-made Appliances' },
    { label: '7-Third Party Processing Delay', value: '7-Third Party Processing Delay' },
    { label: '8-Delay in Eligibility Determination', value: '8-Delay in Eligibility Determination' },
    { label: '9-Original Claim Rejected or Denied Due to a Reason Unrelated to the Billing Limitation Rules', value: '9-Original Claim Rejected or Denied Due to a Reason Unrelated to the Billing Limitation Rules' },
    { label: '10-Administration Delay in the Prior Approval Process', value: '10-Administration Delay in the Prior Approval Process' },
    { label: '11-Other', value: '11-Other' },
    { label: '15-Natural Disaster/State of Emergency', value: '15-Natural Disaster/State of Emergency' },
]
const options = [
    { label: '(A Supportive Hand) LSD3 ADT - Transportation (Ambulatory) (T2003)', value: '(A Supportive Hand) LSD3 ADT - Transportation (Ambulatory) (T2003)' },
    { label: '(A Supportive Hand) LSD3 ADT - Transportation (Non-Ambulatory) (T2003)', value: '(A Supportive Hand) LSD3 ADT - Transportation (Non-Ambulatory) (T2003)' },
    { label: 'CDC - 	LSD3 ADT - Transportation (Ambulatory) (T2003)', value: 'CDC - 	LSD3 ADT - Transportation (Ambulatory) (T2003)' },
    { label: 'CDC - 	LSD3 ADT - Transportation (Non-Ambulatory) (T2003)', value: 'CDC - 	LSD3 ADT - Transportation (Non-Ambulatory) (T2003)' },
    { label: 'CDC - LSD3 - Supported Employment (T2021)', value: 'CDC - LSD3 - Supported Employment (T2021)' },
    { label: 'CDC - LSD3 ADT - 1:1 (S5102)', value: 'CDC - LSD3 ADT - 1:1 (S5102)' },
    { label: 'CDC - LSD3 ADT - 1:10 (S5102)', value: 'CDC - LSD3 ADT - 1:10 (S5102)' },
    { label: 'CDC - LSD3 ADT - 1:3 (S5102)', value: 'CDC - LSD3 ADT - 1:3 (S5102)' },
    { label: 'CDC - LSD3 ADT - 1:5 (S5102)', value: 'CDC - LSD3 ADT - 1:5 (S5102)' },
    { label: 'CDC - LSD3 ADT - 1:6 (S5102)', value: 'CDC - LSD3 ADT - 1:6 (S5102)' },
    { label: 'CDC - LSD3 ADT - Transportation (Ambulatory) $20 Only (T2003)', value: 'CDC - LSD3 ADT - Transportation (Ambulatory) $20 Only (T2003)' },
    { label: 'GENERAL REVENUE - LSD3 ADT - 1:1 (S5102)', value: 'GENERAL REVENUE - LSD3 ADT - 1:1 (S5102)' },
    { label: 'GENERAL REVENUE - LSD3 ADT - 1:10 (S5102)', value: 'GENERAL REVENUE - LSD3 ADT - 1:10 (S5102)' },
    { label: 'GENERAL REVENUE - LSD3 ADT - 1:3 (S5102)', value: 'GENERAL REVENUE - LSD3 ADT - 1:3 (S5102)' },
    { label: 'GENERAL REVENUE - LSD3 ADT - 1:5 (S5102) ', value: 'GENERAL REVENUE - LSD3 ADT - 1:5 (S5102) ' },
    { label: 'GENERAL REVENUE - LSD3 ADT - 1:6 (S5102) ', value: 'GENERAL REVENUE - LSD3 ADT - 1:6 (S5102) ' },
    { label: 'GENERAL REVENUE - LSD3 ADT - Transportation (Ambulatory) (T2003) ', value: 'GENERAL REVENUE - LSD3 ADT - Transportation (Ambulatory) (T2003) ' },
    { label: 'GENERAL REVENUE - LSD3 ADT - Transportation (Non-Ambulatory) (T2003) ', value: 'GENERAL REVENUE - LSD3 ADT - Transportation (Non-Ambulatory) (T2003) ' },
    { label: 'GENERAL REVENUE - Transportation (Ambulatory) $20 Only (T2003) ', value: 'GENERAL REVENUE - Transportation (Ambulatory) $20 Only (T2003) ' },
    { label: 'LSD3 - Supported Employment (T2021) ', value: 'LSD3 - Supported Employment (T2021) ' },
    { label: 'LSD3 ADT - 1:1 (S5102) ', value: 'LSD3 ADT - 1:1 (S5102) ' },
    { label: 'LSD3 ADT - 1:10 (S5102) ', value: 'LSD3 ADT - 1:10 (S5102) ' },
    { label: 'LSD3 ADT - 1:3 (S5102) ', value: 'LSD3 ADT - 1:3 (S5102)' },
    { label: 'LSD3 ADT - 1:5 (S5102) ', value: 'LSD3 ADT - 1:5 (S5102) ' },
    { label: 'LSD3 ADT - 1:6 (S5102) ', value: 'LSD3 ADT - 1:6 (S5102) ' },
    { label: 'LSD3 ADT - Transportation (Ambulatory) (T2003) ', value: 'LSD3 ADT - Transportation (Ambulatory) (T2003) ' },
    { label: 'LSD3 ADT - Transportation (Ambulatory) $20 Only (T2003) ', value: 'LSD3 ADT - Transportation (Ambulatory) $20 Only (T2003) ' },
    { label: 'LSD3 ADT - Transportation (Non-Ambulatory) (T2003) ', value: 'LSD3 ADT - Transportation (Non-Ambulatory) (T2003) ' },
    { label: 'PRIVATE - 	LSD3 ADT - Transportation (Non-Ambulatory) (T2003) ', value: 'PRIVATE - 	LSD3 ADT - Transportation (Non-Ambulatory) (T2003) ' },
    { label: 'PRIVATE - LSD3 ADT - 1:1 (S5102) ', value: 'PRIVATE - LSD3 ADT - 1:1 (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - 1:10 (S5102) ', value: 'PRIVATE - LSD3 ADT - 1:10 (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - 1:3 (S5102) ', value: 'PRIVATE - LSD3 ADT - 1:3 (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - 1:5 (S5102) ', value: 'PRIVATE - LSD3 ADT - 1:5 (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - 1:6 (S5102) ', value: 'PRIVATE - LSD3 ADT - 1:6 (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - ADVANCED (S5102) ', value: 'PRIVATE - LSD3 ADT - ADVANCED (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - MINIMAL (S5102) ', value: 'PRIVATE - LSD3 ADT - MINIMAL (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - MODERATE (S5102) ', value: 'PRIVATE - LSD3 ADT - MODERATE (S5102) ' },
    { label: 'PRIVATE - LSD3 ADT - Transportation (Ambulatory) (T2003) ', value: 'PRIVATE - LSD3 ADT - Transportation (Ambulatory) (T2003) ' },
    { label: 'PRIVATE - LSD3 ADT - Transportation (Ambulatory) $20 Only (T2003) ', value: 'PRIVATE - LSD3 ADT - Transportation (Ambulatory) $20 Only (T2003) ' },
    { label: 'Special Enrollment - LSD3 ADT - 1:1 (S5102) ', value: 'Special Enrollment - LSD3 ADT - 1:1 (S5102) ' },
    { label: 'Special Enrollment - LSD3 ADT - 1:10 (S5102) ', value: 'Special Enrollment - LSD3 ADT - 1:10 (S5102) ' },
    { label: 'Special Enrollment - LSD3 ADT - 1:3 (S5102) ', value: 'Special Enrollment - LSD3 ADT - 1:3 (S5102) ' },
    { label: 'Special Enrollment - LSD3 ADT - 1:5 (S5102) ', value: 'Special Enrollment - LSD3 ADT - 1:5 (S5102) ' },
    { label: 'Special Enrollment - LSD3 ADT - 1:6 (S5102) ', value: 'Special Enrollment - LSD3 ADT - 1:6 (S5102) ' },
    { label: 'Summer Enrollment (S5102) ', value: 'Summer Enrollment (S5102) ' },
]

const NewProfessionalClaimForm = () => {

    const [individual, setIndividual] = useState(false)
    const [name, setName] = useState(data)
    const handleChange = () => {
        setIndividual(!individual)
    }

    const initialValues = {
        note: '',
        comment: '',
        noteReferenceCode: [],
        serviceDescription: [],
        serviceDateFrom: [],
        serviceDateTo: [],
        billingProvider: [],
        renderingProvider: [],
        providerServiceLine: [],
        referringProvider: [],
        serviceFacilityLocation: [],
        signatureOnFire: [],
        placeOfService: [],
        claimFrequencyTypeCode: [],
        medicalAssignmentCode: [],
        informationCode: [],
        patientSignature: [],
        filingIndicator: [],
        benefitsIndicator: [],
        payerResponsibility: [],
        relationToIndividual: [],
        specialProgramCode: [],
        delayReasonCode: []
    }


    return (
        <Formik
            // validationSchema={registrationSchema}
            enableReinitialize
            initialValues={
                initialValues
            }
            onSubmit={(values, { isSubmitting }) => {
                console.log(values)
            }}
        >
            {({ isSubmitting, resetForm }) => (
                <Form>
                    <div className='fv-row mb-7 fv-plugins-icon-container p-5 card'>
                        <div className='card-body'>
                            <h1 className='mb-5'>Professional Claim Generator</h1>
                            <div className='row'>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Select Payer</label>
                                    <Field
                                        as='select'
                                        name='payer'
                                        autoComplete='off'
                                        options={Payer}
                                        component={SelectField}
                                        placeholder='Select Payer'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Billing Provider</label>
                                    <Field
                                        as='select'
                                        name='billingProvider'
                                        autoComplete='off'
                                        options={BillingProviderOptions}
                                        component={SelectField}
                                        placeholder='Select Billing Provider'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Rendering Provider</label>
                                    <Field
                                        as='select'
                                        name='renderingProvider'
                                        autoComplete='off'
                                        options={RenderingProviderOptions}
                                        component={SelectField}
                                        placeholder='Select Rendering Provider'
                                    />
                                </div>
                                <div className="row">
                                    <div className='col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 my-0 mt-6'>
                                        <label className='fw-bold fs-6 mb-0'>
                                            Use Rendering Provider in Service Line
                                            <Field
                                                type='checkbox'
                                                name='providerServiceLine'
                                                value='Use Rendering Provider in Service Line'
                                                className='mx-5'
                                            />
                                        </label>
                                    </div>
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 mt-6' >
                                    <label className='fw-bold fs-6 mb-2' >Referring Provider</label>
                                    <Field
                                        as='select'
                                        name='referringProvider'
                                        autoComplete='off'
                                        options={ReferringProviderOptions}
                                        component={SelectField}
                                        placeholder='Select Referring Provider'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 mt-6 ' >
                                    <label className='fw-bold fs-6 mb-2' >Service Facility Location</label>
                                    <Field
                                        as='select'
                                        name='serviceFacilityLocation'
                                        autoComplete='off'
                                        options={ServiceFacilityOptions}
                                        component={SelectField}
                                        placeholder='Select Service Facility Location'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Signature On Fire</label>
                                    <Field
                                        as='select'
                                        name='signatureOnFire'
                                        autoComplete='off'
                                        options={SignatureOptions}
                                        component={SelectField}
                                        placeholder='Select Signature On Fire'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Place Of Service</label>
                                    <Field
                                        as='select'
                                        name='placeOfService'
                                        autoComplete='off'
                                        options={PlaceOptions}
                                        component={SelectField}
                                        placeholder='Select Place Of Service'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Claim Frequency Type Code</label>
                                    <Field
                                        as='select'
                                        name='claimFrequencyTypeCode'
                                        autoComplete='off'
                                        options={FrequencyTypeOptions}
                                        component={SelectField}
                                        placeholder='Select Claim Frequency Type Code'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Medicare Assignment Code</label>
                                    <Field
                                        as='select'
                                        name='medicalAssignmentCode'
                                        autoComplete='off'
                                        options={MedicareAssignmentOptions}
                                        component={SelectField}
                                        placeholder='Select Medicare Assignment Code'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Release of Information Code</label>
                                    <Field
                                        as='select'
                                        name='informationCode'
                                        autoComplete='off'
                                        options={InformationOptions}
                                        component={SelectField}
                                        placeholder='Select Release of Information Code'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Patient Signature Source Code</label>
                                    <Field
                                        as='select'
                                        name='patientSignature'
                                        autoComplete='off'
                                        options={PatientSignatureOptions}
                                        component={SelectField}
                                        placeholder='Select Patient Signature Source Code'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Claim Filing Indicator</label>
                                    <Field
                                        as='select'
                                        name='filingIndicator'
                                        autoComplete='off'
                                        options={FillingIndicatorOptions}
                                        component={SelectField}
                                        placeholder='Select Claim Filing Indicator'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Assignment of Benefits Indicator</label>
                                    <Field
                                        as='select'
                                        name='benefitsIndicator'
                                        autoComplete='off'
                                        options={BenefitsIndicatorOptions}
                                        component={SelectField}
                                        placeholder='Select Assignment of Benefits Indicator'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Payer Responsibility</label>
                                    <Field
                                        as='select'
                                        name='payerResponsibility'
                                        autoComplete='off'
                                        options={PayerOptions}
                                        component={SelectField}
                                        placeholder='Select Payer Responsibility'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >RelationShip To Individual</label>
                                    <Field
                                        as='select'
                                        name='relationToIndividual'
                                        autoComplete='off'
                                        options={RelationOptions}
                                        component={SelectField}
                                        placeholder='Select RelationShip To Individual'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Special Program Code</label>
                                    <Field
                                        as='select'
                                        name='specialProgramCode'
                                        autoComplete='off'
                                        options={SpecialProgramOptions}
                                        component={SelectField}
                                        placeholder='Select Special Program Code'
                                    />
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Delay Reason Code</label>
                                    <Field
                                        as='select'
                                        name='delayReasonCode'
                                        autoComplete='off'
                                        options={DelayReasonCode}
                                        component={SelectField}
                                        placeholder='Select Special Program Code'
                                    />
                                </div>
                            </div>

                        </div>
                    </div>
                    <div className='fv-row mb-7 fv-plugins-icon-container p-5 card'>
                        <div className='card-body'>
                            <h1 className='mb-5'>Claim Generator Search</h1>
                            <div className="mt-3 alert alert-success">
                                Select Date Range and Service
                            </div>
                            <div className='row'>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 '>
                                    <label className='fw-bold fs-6 mb-2'>Service Date From</label>
                                    <Field
                                        type='date'
                                        name='serviceDateFrom'
                                        className='form-control form-control-solid mb-3 mb-lg-0'
                                        placeholder=''
                                    ></Field>
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 '>
                                    <label className='fw-bold fs-6 mb-2'>Service Date To</label>
                                    <Field
                                        type='date'
                                        name='serviceDateTo'
                                        className='form-control form-control-solid mb-3 mb-lg-0'
                                        placeholder=''
                                    ></Field>
                                </div>
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Service Description/Code</label>
                                    <Field
                                        as='select'
                                        name='serviceDescription'
                                        autoComplete='off'
                                        options={options}
                                        isMulti
                                        component={SelectField}
                                        placeholder='Select Service Description'
                                    />
                                </div>


                            </div>
                            <div className='col'>
                                <button
                                    className='btn  btn-success float-end'
                                    type='button'
                                >
                                    Next
                                </button>
                            </div>
                        </div>

                    </div>
                    <div className='fv-row mb-7 fv-plugins-icon-container p-5 card'>
                        <div className='card-body'>
                            <h1 className='mb-5'>X12-837 Note</h1>
                            <div className="mt-3 alert alert-success">
                                This note will be added to X12-837.
                            </div>
                            <div className="row">
                                <div className='col-col-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3 ' >
                                    <label className='fw-bold fs-6 mb-2' >Note Reference Code</label>
                                    <Field
                                        as='select'
                                        name='noteReferenceCode'
                                        autoComplete='off'
                                        options={NoteReferenceCode}
                                        component={SelectField}
                                        placeholder='- Please Select -'
                                    />
                                </div>
                                <div className='col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 my-3'>
                                    <label className=' fw-bold fs-6 mb-2'>Note</label>
                                    <Field
                                        type="text"
                                        name='note'
                                        className="form-control form-control-solid "
                                        placeholder="">
                                    </Field>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='fv-row mb-7 fv-plugins-icon-container p-5 card'>
                        <div className='card-body'>
                            <h1 className='mb-5'>Claim Generator Search</h1>
                            <div className="mt-3 alert alert-success">
                                Select Date Range and Service
                            </div>
                            <div className='row'>
                                <div className='col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 my-3'>
                                    <label className=' fw-bold fs-6 mb-2'>Comments</label>
                                    <Field
                                        as="textarea"
                                        name='comment'
                                        className="form-control form-control-solid "
                                        placeholder="">
                                    </Field>
                                </div>

                            </div>
                        </div>

                    </div>

                    <div className='d-flex justify-content-start pb-6 mt-6'>
                        <div className='mx-3'>
                            <button
                                // to='/billing/professionalclaim'
                                className='btn btn-primary btn-sm'
                            >
                                Cancel
                            </button>
                        </div>
                        <div>
                            <button
                                className='btn btn-sm btn-success'
                                type='submit'
                            >
                                Submit
                            </button>
                        </div>
                    </div>
                </Form>
            )}
        </Formik>
    )
}

export default NewProfessionalClaimForm